### ISSUE TITLE
Heltec Automation ESP32 LoRa Wireless Tracker 433MHz v1.1 - NO GPS active

### ISSUE THREAD

**Issue by fcupp** [richonguzman/LoRa_APRS_Tracker#140]
I purchased this board (https://www.amazon.com/dp/B0D1QRVNDW?ref=ppx_yo2ov_dt_b_product_details&th=1) several weeks ago.

I flashed it for Meshtastic and the GPS works.  I decided to erase and reflash for LoRa APRS (used 'heltec_wireless_tracker' on selection)

I used the LoRa_APRS_Tracker page here - https://richonguzman.github.io/lora-igate-web-flasher/installer.html

Everything works as far as TX/RX Beacons and if I put in a fixed Lat/Long works well.

I can't seem to get the GPS to become active so I can use as a 'tracker'  I even placed it out in my yard for over 1/2 hour to 
confirm I could get a lock on some sats.

I understand you are working on 'Tracker firmware will soon be available!' and am willing to be a beta tester for you.

Thanks for any assistance/feedback

de KE4PIC Frank

**Comment by richonguzman** [comment]
Hi Frank

you installed the iGate firmware. For now the iGate firmware has not GPS update from the boards as there are no "moving" igates per definition.

but soon I'll add a way to update the gps if a igate is moved from one place to another (not as a mobile igate, but as a new place for the igate)

the tracker firmware web installer has been pushed a little into the future (soon!) because I'm fixing many little things on iGate and Tracker firmware before continuing with web installer for tracker

**Comment by fcupp** [comment]
Thank you for your response and great work on the development in this area.

I look forward to seeing the tracker software and expanding APRS into the LoRa realm.

Again if you need a 'tester' let me know.

73s KE4PIC Frank
